spring:
<<<<<<< HEAD
<<<<<<< HEAD
   mvc:
       view:
           prefix: /
           suffix: .html
   datasource:
       url: jdbc:mariadb://fourwarddb.cowfpof74cuw.ap-northeast-2.rds.amazonaws.com:3306/fourwarddb?userUnicode=true&characterEncoding=UTF-8
       username: fourwarddb
       password: fourwarddb
       sql-script-encoding: UTF-8
   jpa:
       hibernate:
           ddl-auto: update
       properties:
           hibernate:
               dialect: org.hibernate.dialect.MariaDBDialect
=======
=======
>>>>>>> DH
    mvc:
        view:
            prefix: /
            suffix: .html
    datasource:
<<<<<<< HEAD
    # 내꺼 url
        url: jdbc:mariadb://fourwarddb.cowfpof74cuw.ap-northeast-2.rds.amazonaws.com:3306/fourwarddb?userUnicode=true&characterEncoding=UTF-8
        username: fourwarddb
        password: fourwarddb
        sql-script-encoding: UTF-8
    
    jpa:
        
=======
        url: jdbc:mariadb://localhost:3306/mariadb
        username: mariadb
        password: mariadb
        sql-script-encoding: UTF-8
    jpa:
>>>>>>> DH
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
<<<<<<< HEAD
                dialect: org.hibernate.dialect.MariaDBDialect
        
>>>>>>> origin/YJ
=======
                dialect: org.hibernate.dialect.MariaDBDialect
>>>>>>> DH
