spring:
    mvc:
        view:
            prefix: /
            suffix: .html
    datasource:
        # url: jdbc:mariadb://localhost:3306/fourwarddblocal
        # driverClassName: org.mariadb.jdbc.Driver
        # username: fourwarddbyong
        # password: 1234
        url: jdbc:mariadb://fourwarddb.cowfpof74cuw.ap-northeast-2.rds.amazonaws.com:3306/fourwarddb?userUnicode=true&characterEncoding=UTF-8
        username: fourwarddb
        password: fourwarddb
        sql-script-encoding: UTF-8
    jpa:
        # show-sql: true
        # open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect