spring:
   mvc:
       view:
           prefix: /
           suffix: .html
   datasource:
       url: jdbc:mariadb://localhost:3306/mariadb
       username: mariadb
       password: mariadb
       sql-script-encoding: UTF-8
   jpa:
       hibernate:
           ddl-auto: update
       properties:
           hibernate:
               dialect: org.hibernate.dialect.MariaDBDialect