spring:
    mvc:
        view:
            prefix: /
            suffix: .html
    datasource:
        url: jdbc:mariadb://localhost:3306/mariadb
        driverClassName: org.mariadb.jdbc.Driver
        username: mariadb
        password: mariadb
        # url: jdbc:mariadb://fourwarddb.ciybg9cfktgy.ap-northeast-2.rds.amazonaws.com:3306/fourwarddb?userUnicode=true&characterEncoding=UTF-8
        # username: fourwarddb
        # password: fourwarddb
        # sql-script-encoding: UTF-8
    jpa:
        # show-sql: true
        # open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect